### ISSUE TITLE
Im getting a error

### ISSUE THREAD

**Issue by DieBrosHaTi** [Artlfmj/updatebot#5]
C:\Users\Timlol\Desktop\updatebot-main\updatebot-main\node_modules\discord.js\src\rest\RequestHandler.js:298
      throw new DiscordAPIError(data, res.status, request);
            ^

DiscordAPIError: Cannot send an empty message
    at RequestHandler.execute (C:\Users\Timlol\Desktop\updatebot-main\updatebot-main\node_modules\discord.js\src\rest\RequestHandler.js:298:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Users\Timlol\Desktop\updatebot-main\updatebot-main\node_modules\discord.js\src\rest\RequestHandler.js:50:14)
    at async TextChannel.send (C:\Users\Timlol\Desktop\updatebot-main\updatebot-main\node_modules\discord.js\src\structures\interfaces\TextBasedChannel.js:171:15) { 
  method: 'post',
  path: '/channels/885236282261901396/messages',
  code: 50006,
  httpStatus: 400,
  requestData: {
    json: {
      content: undefined,
      tts: false,
      nonce: undefined,
      embeds: undefined,
      components: undefined,
      username: undefined,
      avatar_url: undefined,
      allowed_mentions: undefined,
      flags: undefined,
      message_reference: undefined,
      attachments: undefined,
      sticker_ids: undefined
    },
    files: []
  }
}

**Comment by Artforlfmj** [comment]
Could you please provide information on what causes this issue?

**Comment by DieBrosHaTi** [comment]
when i start the bot

**Comment by Artforlfmj** [comment]
Have you provided a valid token?

**Comment by DieBrosHaTi** [comment]
yes my bot token

**Comment by Artforlfmj** [comment]
Is there anyway you could try to debug all message channel send to see exactly from where it is coming

**Comment by DieBrosHaTi** [comment]
idk

**Comment by Artforlfmj** [comment]
Try putting .catch(e => {
console.log(specific err) }) on each to see

**Comment by Artlfmj** [comment]
So?
